export default CABLES;
declare namespace CABLES {
    export { CGL };
    export { CG };
    export { CGP };
    export { EMBED };
    export { Link };
    export { Port };
    export { Op };
    export { Profiler };
    export { Patch };
    export { Timer };
    export { WEBAUDIO };
    export { Variable };
    export { LoadingStatus };
    export { now };
    export { internalNow };
    export let map: (x: number, _oldMin: number, _oldMax: number, _newMin: number, _newMax: number, _easing: number) => number;
}
import { CGL } from "./cgl/index.js";
import { CG } from "./cg/cg_constants.js";
import { CGP } from "./cgp/index.js";
import { EMBED } from "./embedding.js";
import { Link } from "./core_link.js";
import { Port } from "./core_port.js";
import { Op } from "./core_op.js";
import { Profiler } from "./core_profiler.js";
import Patch from "./core_patch.js";
import { Timer } from "./timer.js";
import { WEBAUDIO } from "./webaudio.js";
import { Variable } from "./sessionvar.js";
import { LoadingStatus } from "./loadingstatus.js";
import { now } from "./timer.js";
import { internalNow } from "./timer.js";
