export default CABLES;
declare namespace CABLES {
    export { CGL };
    export { CG };
    export { CGP };
    export { EMBED };
    export { Link };
    export { Port };
    export { Op };
    export { Profiler };
    export { Patch };
    export { Timer };
    export { WEBAUDIO };
    export { Variable };
    export { LoadingStatus };
    export { now };
    export { internalNow };
    export { Anim };
    export { AnimKey };
    export let shortId: () => string;
    export let uuid: () => UUID;
    export let getShortOpName: (fullname: string) => string;
    export let simpleId: () => number;
    export let clamp: (value: number, min: number, max: number) => number;
    export let map: (x: number, _oldMin: number, _oldMax: number, _newMin: number, _newMax: number, _easing?: number) => number;
    export let shuffleArray: (array: any[] | Float32Array) => any[] | Float32Array;
    export let generateUUID: () => UUID;
    export let prefixedHash: (str: string, prefix?: string) => string;
    export let smoothStep: (perc: number) => number;
    export let smootherStep: (perc: number) => number;
    export let cacheBust: (url?: string) => string;
    export let copyArray: (src: any[], dst: any[]) => any[];
    export let basename: (url: string) => string;
    export let logStack: () => void;
    export let filename: (url: string) => string;
    export let ajaxSync: (url: any, cb: any, method: any, post: any, contenttype: any) => void;
    export let ajax: (url: any, cb: any, method: any, post: any, contenttype: any, jsonP: any, headers?: {}, options?: {}) => void;
    export let request: (options: any) => void;
    export let logErrorConsole: (initiator: any, ...args: any[]) => void;
    export let isNumeric: typeof utils.isNumeric;
    export let isArray: typeof utils.isArray;
    export let float32Concat: typeof utils.float32Concat;
    export let uniqueArray: typeof utils.uniqueArray;
    export { CGState };
}
import { CGL } from "./cgl/index.js";
import { CG } from "./cg/cg_constants.js";
import { CGP } from "./cgp/index.js";
import { EMBED } from "./embedding.js";
import Link from "./core_link.js";
import Port from "./core_port.js";
import Op from "./core_op.js";
import Profiler from "./core_profiler.js";
import Patch from "./core_patch.js";
import { Timer } from "./timer.js";
import { WEBAUDIO } from "./webaudio.js";
import { Variable } from "./sessionvar.js";
import LoadingStatus from "./loadingstatus.js";
import { now } from "./timer.js";
import { internalNow } from "./timer.js";
import Anim from "./anim.js";
import AnimKey from "./anim_key.js";
import * as utils from "./utils.js";
import { CGState } from "./cg/cg_state.js";
