export default class Framebuffer2 {
    constructor(cgl: any, w: any, h: any, options: any);
    _log: Logger;
    Framebuffer2DrawTargetsDefault: any[];
    Framebuffer2BlittingFramebuffer: any;
    Framebuffer2FinalFramebuffer: any;
    _cgl: any;
    _width: number;
    _height: number;
    valid: boolean;
    _depthRenderbuffer: any;
    _frameBuffer: any;
    _textureFrameBuffer: any;
    _colorRenderbuffers: any[];
    _drawTargetArray: any[];
    _disposed: boolean;
    _options: any;
    name: any;
    _numRenderBuffers: any;
    _colorTextures: Texture[];
    clearColors: number[][];
    _textureDepth: Texture;
    getWidth(): number;
    getHeight(): number;
    getGlFrameBuffer(): any;
    getDepthRenderBuffer(): any;
    getTextureColor(): Texture;
    getTextureColorNum(i: any): Texture;
    getTextureDepth(): Texture;
    setFilter(f: any): void;
    delete(): void;
    dispose(): void;
    setSize(w: any, h: any): void;
    renderStart(): void;
    clear(): void;
    renderEnd(): void;
}
import { Logger } from "cables-shared-client";
import { Texture } from "./cgl_texture.js";
