export class ProfileData {
    constructor(cgl: any);
    _cgl: any;
    _lastTime: number;
    pause: boolean;
    profileUniformCount: number;
    profileShaderBinds: number;
    profileShaderCompiles: number;
    profileVideosPlaying: number;
    profileMVPMatrixCount: number;
    profileEffectBuffercreate: number;
    profileShaderGetUniform: number;
    profileFrameBuffercreate: number;
    profileMeshSetGeom: number;
    profileTextureNew: number;
    profileGenMipMap: number;
    profileOnAnimFrameOps: number;
    profileFencedPixelRead: number;
    profileMainloopMs: number;
    profileMeshDraw: number;
    profileTextureEffect: number;
    profileTexPreviews: number;
    shaderCompileTime: number;
    profileMeshNumElements: number;
    profileMeshAttributes: number;
    profileSingleMeshAttribute: any[];
    heavyEvents: any[];
    doProfileGlQuery: boolean;
    glQueryData: {};
    clear(): void;
    profileTextureResize: number;
    profileTextureDelete: number;
    profileNonTypedAttrib: number;
    profileNonTypedAttribNames: string;
    profileFramebuffer: number;
    clearGlQuery(): void;
    addHeavyEvent(event: any, name: any, info: any): void;
}
