export const CGL: {
    BLEND_NONE: number;
    BLEND_NORMAL: number;
    BLEND_ADD: number;
    BLEND_SUB: number;
    BLEND_MUL: number;
    DEG2RAD: number;
    RAD2DEG: number;
    SHADERVAR_VERTEX_POSITION: string;
    SHADERVAR_VERTEX_NUMBER: string;
    SHADERVAR_VERTEX_NORMAL: string;
    SHADERVAR_VERTEX_TEXCOORD: string;
    SHADERVAR_INSTANCE_MMATRIX: string;
    SHADERVAR_VERTEX_COLOR: string;
    SHADERVAR_INSTANCE_INDEX: string;
    SHADERVAR_UNI_PROJMAT: string;
    SHADERVAR_UNI_VIEWMAT: string;
    SHADERVAR_UNI_MODELMAT: string;
    SHADERVAR_UNI_NORMALMAT: string;
    SHADERVAR_UNI_INVVIEWMAT: string;
    SHADERVAR_UNI_INVPROJMAT: string;
    SHADERVAR_UNI_MATERIALID: string;
    SHADERVAR_UNI_OBJECTID: string;
    SHADERVAR_UNI_VIEWPOS: string;
    Framebuffer2: typeof Framebuffer2;
    Geometry: typeof Geometry;
    BoundingBox: typeof BoundingBox;
    Marker: Function;
    WirePoint: Function;
    WireCube: Function;
    MatrixStack: typeof MatrixStack;
    Mesh: typeof Mesh;
    MESH: typeof MESH;
    ShaderLibMods: typeof ShaderLibMods;
    Shader: typeof Shader;
    Uniform: typeof Uniform;
    MESHES: typeof MESHES;
    Context: typeof Context;
    Texture: typeof Texture;
    TextureEffect: typeof TextureEffect;
    isWindows: any;
    getWheelSpeed: (event: any) => number;
    getWheelDelta: (event: any) => number;
    onLoadingAssetsFinished: any;
    ProfileData: typeof ProfileData;
    UniColorShader: typeof UniColorShader;
};
import Framebuffer2 from "./cgl_framebuffer2.js";
import { Geometry } from "../cg/cg_geom.js";
import { BoundingBox } from "../cg/cg_boundingbox.js";
import { MatrixStack } from "../cg/cg_matrixstack.js";
import { Mesh } from "./cgl_mesh.js";
import { MESH } from "./cgl_mesh.js";
import { ShaderLibMods } from "./cgl_shader_lib.js";
import { Shader } from "./cgl_shader.js";
import { Uniform } from "./cgl_shader_uniform.js";
import { MESHES } from "./cgl_simplerect.js";
import { Context } from "./cgl_state.js";
import { Texture } from "./cgl_texture.js";
import { TextureEffect } from "./cgl_textureeffect.js";
import { ProfileData } from "./cgl_profiledata.js";
import { UniColorShader } from "./cgl_unicolorshader.js";
