export default CgUniform;
declare class CgUniform {
    constructor(__shader: any, __type: any, __name: any, _value: any, _port2: any, _port3: any, _port4: any, _structUniformName: any, _structName: any, _propertyName: any);
    _log: Logger;
    _type: any;
    _name: any;
    _shader: any;
    _value: any;
    _oldValue: any;
    _port: Port;
    _structName: any;
    _structUniformName: any;
    _propertyName: any;
    needsUpdate: boolean;
    shaderType: any;
    comment: any;
    set: any;
    setValue: any;
    updateValue: any;
    _port2: any;
    _port3: any;
    _port4: any;
    getType(): any;
    get type(): any;
    get name(): any;
    getName(): any;
    getValue(): any;
    getShaderType(): any;
    isStructMember(): boolean;
    updateFromPort4f(): void;
    updateFromPort3f(): void;
    updateFromPort2f(): void;
    updateFromPort(): void;
}
import { Logger } from "cables-shared-client";
import { Port } from "../core_port.js";
